# Generated by Django 4.2.9 on 2024-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=20)),
                ('academicyear', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('Coursecode', models.CharField(max_length=20)),
                ('CourseTitle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_id', models.BigIntegerField(unique=True)),
                ('FullName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('password', models.CharField(default='klu123', max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.BigIntegerField(unique=True)),
                ('FullName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('Program', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('password', models.CharField(default='klu123', max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
