# Generated by Django 5.0.1 on 2024-02-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_course_academicyear_alter_course_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech')], default='B.Tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(),
        ),
    ]
