# Generated by Django 5.0.1 on 2024-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_facultycoursemapping_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CSE(R)', 'CSE(Regular)'), ('CSE(H)', 'CSE(Honors)'), ('CSIT', 'CS&IT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facultycoursemapping',
            name='type',
            field=models.BooleanField(verbose_name='Faculty Type'),
        ),
    ]
